root: true

env:
  browser: true
  node: true
  es6: true

extends: 
  - eslint:recommended

parserOptions:
  ecmaVersion: 2021

rules:
  semi: error
  quotes: [error, single]

# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       python: 3.11

#   build:
#     commands:
#       - pip install --upgrade pip
#       - pip install -r requirements.txt
#       - pip install pylint
#       - echo "Build started on `date`"
#       - echo "Compiling the code"
#       - echo "$CODEBUILD_SRC_DIR"

#   post_build:
#     commands:
#       - python --version
#       - pylint $CODEBUILD_SRC_DIR/*.py
#       - echo "$CODEBUILD_SRC_DIR"
#       - pylint $CODEBUILD_SRC_DIR/sandevopsproject/*.py

# artifacts:
#   files:
#     - '**/*'
