version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - curl -O https://downloads.sourceforge.net/project/findbugs/findbugs/3.0.1/findbugs-3.0.1.zip
      - unzip findbugs-3.0.1.zip
  pre_build:
    commands:
      - export FINDBUGS_HOME=$PWD/findbugs-3.0.1
  build:
    commands:
      - java -jar $FINDBUGS_HOME/lib/findbugs.jar -textui <path_to_your_java_classes_directory>




# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       python: 3.11

#   build:
#     commands:
#       - pip install --upgrade pip
#       - pip install -r requirements.txt
#       - pip install pylint
#       - echo "Build started on `date`"
#       - echo "Compiling the code"
#       - echo "$CODEBUILD_SRC_DIR"

#   post_build:
#     commands:
#       - python --version
#       - pylint $CODEBUILD_SRC_DIR/*.py
#       - echo "$CODEBUILD_SRC_DIR"
#       - pylint $CODEBUILD_SRC_DIR/sandevopsproject/*.py

# artifacts:
#   files:
#     - '**/*'
