version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - apt-get update
      - apt-get install -y maven
  pre_build:
    commands:
      - echo "Navigating to the project directory"
      - cd ems   # Change to your project directory
      - echo "Building Spring Boot application"
      - mvn clean package -X -DskipTests
  build:
    commands:
      - echo "Build completed, creating deployment artifact"
      - mv ems/target/*.jar app.jar  # Adjust the path to your JAR file accordingly
  post_build:
    commands:
      - echo "Post build tasks"
artifacts:
  files:
    - app.jar

