version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - apt-get update
      - apt-get install -y maven
  pre_build:
    commands:
      - echo "Building Spring Boot application"
      - mvn clean package -X
  build:
    commands:
      - echo "Build completed, creating deployment artifact"
      - mv target/*.jar app.jar
  post_build:
    commands:
      - echo "Post build tasks"
artifacts:
  files:
    - app.jar
